# Generated by Django 4.0.3 on 2022-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('units', models.IntegerField(max_length=100)),
                ('sales', models.IntegerField(max_length=100)),
                ('dateolds', models.CharField(max_length=100)),
            ],
        ),
    ]
